config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "/", to: redirect("/#{I18n.default_locale}")

  %w(facebook twitter google linkedin).each do |provider|
    devise_scope :user do
      get "/users/auth/:provider" => "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "users" }, as: :"user_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end

    devise_scope :company do
      get "/companies/auth/:provider", to: "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "companies" }, as: :"company_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    authenticate :admin_user do
      mount Sidekiq::Web => "/sidekiq"
    end
    ActiveAdmin.routes(self) rescue nil # when setting up the app routes are loaded before DB schema and ActiveAdmin can't establish connection

    devise_for :admin_users, ActiveAdmin::Devise.config
    devise_for :companies, controllers: {
      registrations: "companies/registrations",
      sessions: "companies/sessions",
      passwords: "companies/passwords",
    }
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
    }

    devise_scope :user do
      get "/users/passwords/reset_success" => "users/passwords#reset_success"
      get "/users/passwords/new_pass_success" => "users/passwords#new_pass_success"
      get "/users/registrations/success" => "users/registrations#success"
    end

    devise_scope :company do
      get "/companies/passwords/reset_success" => "companies/passwords#reset_success"
      get "/companies/passwords/new_pass_success" => "companies/passwords#new_pass_success"
      get "/companies/registrations/success" => "companies/registrations#success"
    end

    resources :leads, only: %i( new create )
    resources :attribute_kinds
    resources :service_kinds

    resources :users do
      member do
        get :services
        get :companies
      end
    end

    resources :companies do
      member do
        get :items
        get :services
        get :activate
      end
    end

    resources :items do
      collection do
        get :get_attributes
      end
      member do
        post :transfer
        post :receive
        get :show_pdf
      end
      resources :services do
        member do
          patch :approve
          patch :decline
        end
      end
      resources :charts, as: :key_performance_indicators, only: %i(index)
    end

    # TODO: remove this routes, must use that one services rousource inside the items
    resources :services do
      member do
        patch :approve
        patch :decline
      end
    end

    resources :checkouts, only: %i( show new create )

    get           "/dashboard" => "items#dashboard",          as: :dashboard
    get           "/dashboard" => "items#dashboard",          as: :home
    get         "/item/:token" => "items#show_for_company",   as: :show_for_company
    get "/item/service/:token" => "services#company_service", as: :company_service
    get           "/addresses" => "addresses#search"
    get               "/about" => "static_pages#about",       as: :static_pages_about
    get            "/security" => "static_pages#security",    as: :static_pages_security
    get         "/for_investors" => "static_pages#for_investors", as: :static_pages_for_investors
    get             "/careers" => "static_pages#careers",     as: :static_pages_careers
    get                "/lead" => "static_pages#lead",        as: :static_pages_lead
    get               "/terms" => "static_pages#terms",       as: :static_pages_terms
    get                 "/new" => "static_pages#home",        as: :static_pages_home
    get            "/donation" => "checkouts#new",            as: :donation

    post "/notifications/:id/read" => "notifications#read", constraints: ->(request) { request.xhr? }

    authenticated :user do
      root "items#dashboard", as: :authenticated_root
      get "/profile" => "users#profile"
    end

    authenticated :company do
      root "items#dashboard_company", as: :authenticated_root_company
      get "/profile" => "companies#profile"
    end
    # Temporary changed root route
    if ENV["HOME_PAGE_TRIGGER"].present?
      root "static_pages#home"
    else
      root "leads#new"
    end

    resources :blockchain_infos, path: "blockchain", param: "hash"
  end

  get "*path",
    constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" },
    to: redirect do |params, request|
      "#{request.protocol}#{request.host_with_port}/#{I18n.default_locale}/#{params[:path]}?#{request.params.to_query}"
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
         :trackable, :validatable

  include OauthableModel

  has_many :items, as: :user, dependent: :destroy
  has_many :transferring_items, class_name: "Item",
                                foreign_key: :transferring_to_id
  has_many :services, through: :items
  has_many :blockchain_transaction_data, through: :services
  has_many :assigned_services, foreign_key: :approver_id,
                               class_name: "Service",
                               as: :approver
  has_many :notifications

  validates :first_name, presence: true
  validates :phone, phone: true, allow_blank: true
  validates :postal_code, zipcode: { country_code_attribute: :country_short }, allow_blank: true

  mount_uploader :picture, AccountUploader

  def country_object
    ISO3166::Country.find_country_by_name country
  end

  def country_short
    country_object.try :alpha2
  end

  def create_notification(event_name, *args)
    notification = notifications.build
    message = notification.build_message(event_name, *args)
    notification.message = message
    notification.save
    notification
  end

  def to_blockchain_hash
    {
      id: id
    }
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  first_name             :string
#  last_name              :string
#  phone                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  country                :string
#  city                   :string
#  address                :string
#  postal_code            :string
#  notice                 :string
#  picture                :string
#
# Indexes
#
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController

  layout 'new'

  prepend_before_action :require_no_authentication, except: :new_pass_success

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  protected

  def after_resetting_password_path_for(_)
    users_passwords_new_pass_success_path
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(_)
    users_passwords_reset_success_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include Accessible

  layout 'new'

  before_action :check_user, except: :success
  before_filter :configure_sign_up_params, only: [:create]
  before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    ActiveRecord::Base.transaction do
      super
      if resource.valid?
        resource.after_sign_up_actions!
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone, :country, :city, :address, :postal_code, :notice, :picture])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_)
    users_registrations_success_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  layout 'new'
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'item'
  before_action :set_user, only: [:show, :edit, :update, :destroy, :items, :services, :companies]
  before_action :authenticate_user!

  def show
    redirect_to edit_user_path(@user)
  end

  def edit
    authorize @user
  end

  def services
    @pending_services = current_user.services.pending
    @declined_services = current_user.assigned_services.declined
    @services_for_approval = current_user.assigned_services.pending
  end

  def companies
    @all_companies = Company.user_companies(@user).distinct
  end

  def update
    authorize @user
    if @user.update(user_params)
      bypass_sign_in @user
      redirect_to root_path, notice: t(".notice")
    else
      render :edit
    end
  end

  def destroy
    authorize @user
    if @user.valid_password?(params[:user][:password])
      sign_out @user
      @user.destroy
      redirect_to root_path, notice: t(".success")
    else
      redirect_to edit_user_url, notice: t(".password_invalid")
    end
  end

  def profile
    redirect_to edit_user_path(current_user)
  end

  private

  def set_user
    @user = User.find(params[:id])
    @user = @user.present? ? @user.decorate : @user
  end

  def user_params
    country = ISO3166::Country.find_country_by_name(params[:user][:country]) ||
              ISO3166::Country.new(params[:user][:country])
    params[:user][:country] = country.name if country.present?
    columns = [:first_name, :last_name, :phone, :country, :city, :address,
      :postal_code, :notice, :picture, :email]
    columns << [:password, :password_confirmation] if params[:user][:password].present?
    params.require(:user).permit(columns)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div  class="service_create_main_form"
      ng-controller="AccountEditController as accountEditController"
      ng-click="clickedBlank()"
      ng-init='accountEditController.setProfile(
         <%= @user.to_json(only: %i( country_short city address postal_code ), methods: %i( country_short profile_picture_url )).html_safe %>
       )'>
  <div class="left_form_service_create margin">
    <div class="form_service_create">
      <div class="destroy_user">
        <h1>
          <%= t(".delete_my_account") %>
        </h1>
        <%= form_for @user, method: :delete do |f| %>
          <p>
            <%= t(".password") %>
          </p>
          <%= f.password_field :password, autocomplete: :off, placeholder: t(".password_placeholder")  %>
          <div class="delete_button">
            <%= f.submit value: t(".delete_link"), data: { confirm: t(".confirm_delete") } %>
          </div>
        <% end %>
      </div>

      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div class="error_explanation">
            <p><%= t(".errors_user") %></p>
          </div>
        <% end %>
        <ol>
          <div class="price">
            <span class="field_name">
              <li><%= f.label :email %></li>
            </span>
            <%= f.email_field :email,  :disabled => true  %>
          </div>

          <div class="half_form_field half first first_name">
            <span class="field_name">
              <li><%= f.label :first_name %></li>
            </span>
            <%= f.text_field :first_name, autofocus: true, placeholder: t(".name_placeholder")  %>
          </div>

          <div class="half_form_field half">
            <span class="field_name">
              <li><%= f.label :last_name %></li>
            </span>
            <%= f.text_field :last_name, placeholder: t(".last_name_placeholder")  %>
          </div>

          <div class="half_form_field first">
            <span class="field_name">
              <li><%= f.label :postal_code %></li>
            </span>
            <%= f.text_field :postal_code, placeholder: t(".postal_placeholder"), :"ng-model" => "postalCode", :"ng-change" => "changedPostalCode(\"#{I18n.locale}\")" %>
            <ul class="hint-list" ng-show="addresses.length > 0">
              <li ng-click="addressSelected()" ng-repeat="address in addresses">{{address.formatted_address}}</li>
            </ul>
          </div>

          <div class="half_form_field half first">
            <span class="field_name">
              <li><%= f.label :country %></li>
            </span>
            <%= f.country_select :country, {prompt: t(".select_country")}, :"ng-model" => "country", :"ng-value" => "{{country}}" %>
          </div>

          <div class="half_form_field half city">
            <span class="field_name">
              <li><%= f.label :city %></li>
            </span>
            <%= f.text_field :city, placeholder: t(".city_placeholder"), :"ng-value" => "city" %>
          </div>

          <div class="price">
            <span class="field_name">
              <li><%= f.label :address %></li>
            </span>
            <%= f.text_field :address, placeholder: t(".address_placeholder"), :"ng-model" => "formattedAddress"  %>
          </div>

          <div class="half_form_field margin first">
            <span class="field_name">
              <li><%= f.label :phone %></li>
            </span>
            <%= f.text_field :phone, placeholder: t(".phone_placeholder")  %>
          </div>
        </ol>

        <div class="line"></div>

        <div class="change_password">
          <h1><%= t(".change_password") %></h1>
          <div class="half_form_field half first">
            <p class="field_name">
              <%= t(".original_password") %>
            </p>
            <%= f.password_field :password, autocomplete: :off, placeholder: t(".password_placeholder")  %>
          </div>

          <div class="half_form_field half">
            <p class="field_name">
              <%= t(".new_password") %>
            </p>
            <%= f.password_field :password_confirmation, autocomplete: :off, placeholder: t(".confirmation_placeholder")  %>
          </div>
        </div>
        <div class="line"></div>

        <div class="notification_confirmation">
          <h1><%= t(".notifications") %></h1>
          <div class="select">
            <label>
              <input type="checkbox" checked/>
              <i>
                <%= image_tag "select.png" %>
              </i>
              <span>
                <%= t(".receive_notifications") %>
              </span>
            </label>
          </div>
        </div>

        <div class="line"></div>
        <div class="user_destroy_place"></div>
        <div class="line"></div>
         <div class="form-actions user">
          <%= f.submit t(".confirm") %>
          <%= link_to t(".discard"), dashboard_path %>
        </div>
      </div>
    </div>

    <div class="right_form_service_create">
      <p class="field_name">
        <%= t(".picture", formats: picture_formats) %>
      </p>
      <div class="image user {{ newPhotoAttached[0] ? 'with_photo' : 'without_photo_input' }}" style="background: url({{imagePreview[0] || images[0]}}) no-repeat center center; background-size: cover;">
        <div class="blank_image">+</div>
        <%= f.file_field :picture,
                         class: 'inputfile',
                         :"data-file" => "true",
                         :"data-index" => 0,
                         :"accept" => "image/jpg, image/jpeg, image/png" %>
      </div>
    <% end %>
    <div class="service_form_info">
      <p>
        <%= t(".title") %>
      </p>
      <span>
        <%= t(".text") %>
      </span>
    </div>
  </div>
</div>

app/views/users/companies.html.erb
<div class="margin_left"><p id="notice"><%= notice %></p>

<h1>Companies</h1>
  <% @all_companies.each do |company| %>
  <div style="width: 300px; height: 210px; float: left;">


    <div class="thumbnail_grid" style="margin: 10px 10px 0 0;">
      <%= picture_show(company) %>
    </div>

  </div><p style="margin-top: 230px"><strong ><%= company.name %></strong></p><% end %>
<br>
  <%= link_to 'Back', @user,  class: "buttonsuser" %>
</div>

app/views/users/edit.html.erb
<div class="service_create_identity">
  <h1><%= t(".my_account") %></h1>
  <span class="green">
    <%= @user.items.count %> <%= t(".items") %>
  </span>
  <span class="grey_text">
    <%= @user.services.count %> <%= t(".services") %>
  </span>
</div>

<%= render 'form' %>

app/views/users/services.html.erb
<div class="margin_left">
<p id="notice"><%= notice %></p>

<h1>Services:</h1>



<h1>pending </h1>


<h1>approved </h1>

<% @pending_services.each do |service| %>
      <div class="servicelist">
      <div style="width: 290px; height: 270px; float: left; margin-bottom: 20px">
      <strong><br><%= service.created_at %></strong>
    <div class="thumbnail_grid">
      <%= service_picture_show(service) %>
    </div>
    </div>

      <strong><br><% service.action_kinds.each do |action_kind| %>
          <%= "#{action_kind.title}" %>
      <% end %>
      <br></strong>
    <% service.service_fields.each do |service_field| %>
            <%= service_field.service_kind.title %><br>
         <%= service_field.text %>
    <% end %>

      <%= link_to "See to related item", service.item, class: "buttonsuser",id: "buttonsuserwidth" %>
    <strong style="margin-left: 40%"><%= number_to_currency(service.price , unit: "€") %></strong>
    <p style="color: green;">Service is approved</p>
      </div>
<% end %>

<h1>declined </h1>

<% @services_for_approval.each do |service| %>

      <div class="servicelist">
      <div style="width: 290px; height: 270px; float: left; margin-bottom: 20px">
      <strong><br><%= service.created_at %></strong>
    <div class="thumbnail_grid">
      <%= service_picture_show(service) %>
    </div>
    </div>

      <strong><br><% service.action_kinds.each do |action_kind| %>
          <%= "#{action_kind.title}" %>
      <% end %>
      <br></strong>
    <% service.service_fields.each do |service_field| %>
            <%= service_field.service_kind.title %><br>
         <%= service_field.text %>
    <% end %>

      <%= link_to "See to related item", service.item, class: "buttonsuser",id: "buttonsuserwidth" %>
    <strong style="margin-left: 40%"><%= number_to_currency(service.price , unit: "€") %></strong>
    <p style="color: red;">Service is declined</p>
      </div>
<% end %>

  <div style="width: 100%">
  <%= link_to 'Back', @user,  class: "buttonsuser" %></div>
</div>

app/views/users/show.html.erb
<div class="margin_left">
  <p id="notice"><%= notice %></p>
<div class="thumbnail" >
  <%= picture_show(@user) %>
</div>
<div  >
  <p id="information_margin " class="first_name">
<span>
  <strong>
    <%= @user.first_name %>
  </strong>
</span>
    <span>
  <strong>
    <%= @user.last_name %>
  </strong>
</span>
  </p>
  <p id="information_margin">
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <p id="information_margin">
    <strong>Phone:</strong>
    <%= @user.phone %>
  </p>
  <p id="information_margin">
    <strong>Country:</strong>
    <%= @user.country %>
  </p>

  <p id="information_margin">
    <strong>City:</strong>
    <%= @user.city %>
  </p>

  <p id="information_margin">
    <strong>Address:</strong>
    <%= @user.address %>
  </p>

  <p id="information_margin">
    <strong>Postal code:</strong>
    <%= @user.postal_code %>
  </p>

  <p>
    <span><%= link_to "All items & service history "   "#{@unconfirmed_count > 0 ? " ! ""(#{@unconfirmed_count})"" new" : ""}", items_path, class: "buttonsuser" %></span>
    <span><%= link_to 'Create Item', new_item_path, class: "buttonsuser" %></span>
    <span><%= link_to t(".update_link"), edit_user_path(@user), class: "buttonsuser" %></span>
    <span><%= link_to t(".delete_link"), user_path(@user), method: :delete,:data => {:confirm => t(".confirm_delete")}, class: "buttonsuser" %></span>
  </p>
</div>
<% if @last_items.present?%>
      <h1><br>My last items</h1>
      <div>
        <% @last_items.each do |item| %>
            <%= link_to item do %>
            <div class="show_tile" style="margin-bottom: 50px">
              <div class="thumbnail_grid" style="height: 120px; width: 120px; " >
                <%= service_picture_show(item) %>
              </div>
              <strong><%=item.title%></strong>
              <span><br><%= item.created_at.strftime("%F") %></span>
            </div>
                <% end %>
        <% end %>
        <br> <br> <br><br></div>
        <span><%= link_to "All items #{@unconfirmed_count > 0 ? "(#{@unconfirmed_count})" : ""}", items_path, class: "buttonsuser"%><br></span>

<% else %>
      <div style="background-color: #D8D8D8; padding:0 20px 20px 20px; max-width: 300px">
        <p>Here you will see service for each of your item. Please add your first item and track your service!</p>
      <span ><%= link_to 'Create Item', new_item_path, class: "buttonsuser" %></span>
      </div>
<% end %>
  <% if @last_services.present?%>
<h1><br>Last services</h1>
<div>
  <% @last_services.each do |service| %>
    <div class="show_tile">
      <div class="thumbnail_grid" style="height: 90px; width: 90px;" >
        <%= service_picture_show(service) %>
      </div>
      <span><% service.action_kinds.each do |action_kind| %></span>
          <%= "#{action_kind.title}" %>
      <% end %>
      <span><br><%= service.created_at.strftime("%F") %></span>
</div>
  <% end %>
  <br> <br> <br>
  <span><%= link_to 'Show all services', services_user_path(@user), class: "buttonsuser" %><br></span>
</div>
  <% else %>
      <div style="background-color: #D8D8D8; padding:0 20px 20px 20px; max-width: 300px">
        <p>Here you will see last services for each of your item. Please add your first item and track your service!</p>

      </div>
  <% end %>

  <% if @last_companies.present?%>
<h1>Companies that did services</h1>
<div>

  <% @last_companies.each do |company| %>
      <div class="show_tile">
      <div class="thumbnail_grid" style="height: 90px; width: 90px;">
        <%= picture_show(company) %>
      </div>
      <%= company.name %>

</div>
  <% end %>
  <br> <br><br>
  <span ><%= link_to 'Show all companies', companies_user_path(@user), class: "buttonsuser" %></span>
  <% else %>
      <div style="background-color: #D8D8D8; padding:0 20px 20px 20px; max-width: 300px">
        <p>Here you will see companies that have made services for you.</p>

      </div>
  <% end %>

</div>
</div>