config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "/", to: redirect("/#{I18n.default_locale}")

  %w(facebook twitter google linkedin).each do |provider|
    devise_scope :user do
      get "/users/auth/:provider" => "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "users" }, as: :"user_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end

    devise_scope :company do
      get "/companies/auth/:provider", to: "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "companies" }, as: :"company_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    authenticate :admin_user do
      mount Sidekiq::Web => "/sidekiq"
    end
    ActiveAdmin.routes(self) rescue nil # when setting up the app routes are loaded before DB schema and ActiveAdmin can't establish connection

    devise_for :admin_users, ActiveAdmin::Devise.config
    devise_for :companies, controllers: {
      registrations: "companies/registrations",
      sessions: "companies/sessions",
      passwords: "companies/passwords",
    }
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
    }

    devise_scope :user do
      get "/users/passwords/reset_success" => "users/passwords#reset_success"
      get "/users/passwords/new_pass_success" => "users/passwords#new_pass_success"
      get "/users/registrations/success" => "users/registrations#success"
    end

    devise_scope :company do
      get "/companies/passwords/reset_success" => "companies/passwords#reset_success"
      get "/companies/passwords/new_pass_success" => "companies/passwords#new_pass_success"
      get "/companies/registrations/success" => "companies/registrations#success"
    end

    resources :leads, only: %i( new create )
    resources :attribute_kinds
    resources :service_kinds

    resources :users do
      member do
        get :services
        get :companies
      end
    end

    resources :companies do
      member do
        get :items
        get :services
        get :activate
      end
    end

    resources :items do
      collection do
        get :get_attributes
      end
      member do
        post :transfer
        post :receive
        get :show_pdf
      end
      resources :services do
        member do
          patch :approve
          patch :decline
        end
      end
      resources :charts, as: :key_performance_indicators, only: %i(index)
    end

    # TODO: remove this routes, must use that one services rousource inside the items
    resources :services do
      member do
        patch :approve
        patch :decline
      end
    end

    resources :checkouts, only: %i( show new create )

    get           "/dashboard" => "items#dashboard",          as: :dashboard
    get           "/dashboard" => "items#dashboard",          as: :home
    get         "/item/:token" => "items#show_for_company",   as: :show_for_company
    get "/item/service/:token" => "services#company_service", as: :company_service
    get           "/addresses" => "addresses#search"
    get               "/about" => "static_pages#about",       as: :static_pages_about
    get            "/security" => "static_pages#security",    as: :static_pages_security
    get         "/for_investors" => "static_pages#for_investors", as: :static_pages_for_investors
    get             "/careers" => "static_pages#careers",     as: :static_pages_careers
    get                "/lead" => "static_pages#lead",        as: :static_pages_lead
    get               "/terms" => "static_pages#terms",       as: :static_pages_terms
    get                 "/new" => "static_pages#home",        as: :static_pages_home
    get            "/donation" => "checkouts#new",            as: :donation

    post "/notifications/:id/read" => "notifications#read", constraints: ->(request) { request.xhr? }

    authenticated :user do
      root "items#dashboard", as: :authenticated_root
      get "/profile" => "users#profile"
    end

    authenticated :company do
      root "items#dashboard_company", as: :authenticated_root_company
      get "/profile" => "companies#profile"
    end
    # Temporary changed root route
    if ENV["HOME_PAGE_TRIGGER"].present?
      root "static_pages#home"
    else
      root "leads#new"
    end

    resources :blockchain_infos, path: "blockchain", param: "hash"
  end

  get "*path",
    constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" },
    to: redirect do |params, request|
      "#{request.protocol}#{request.host_with_port}/#{I18n.default_locale}/#{params[:path]}?#{request.params.to_query}"
    end
end

app/views/shared/_form_errors.html.erb
<% if object.errors.present? %>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message.html_safe %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_google_analytics.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-120223573-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-120223573-1');
</script>

app/views/shared/_login_form.html.erb
                  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                    <p class="alert"><%= alert %></p>
                    <div class="mail">
                      <%= f.email_field :email, autofocus: true, placeholder: t(".email") %>
                      <%= inline_svg "mail_ico.svg" %>
                    </div>

                    <div class="password">
                      <input autocomplete="off" placeholder="<%= t(".pass") %>" type="{{type}}" name="<%= resource_name %>[password]" id="<%= resource_name %>_password">
                      <%= inline_svg "pass_ico.svg" %>
                    </div>
                    <div class="signup_info_right">
                      <%= link_to t(".forgot"), new_password_path(resource_name) %>
                    </div>
                    <div class="signup_but">
                      <%= f.submit t(".sign_in") %>
                      <%= link_to "&nbsp;".html_safe, send(:"#{resource_name}_google_omniauth_authorize_path"), class: "login-button google" %>
                      <%= link_to "&nbsp;".html_safe, send(:"#{resource_name}_facebook_omniauth_authorize_path"), class: "login-button facebook" %>
                      <%= link_to "&nbsp;".html_safe, send(:"#{resource_name}_twitter_omniauth_authorize_path"), class: "login-button twitter" %>
                      <%= link_to "&nbsp;".html_safe, send(:"#{resource_name}_linkedin_omniauth_authorize_path"), class: "login-button linkedin" %>
                    </div>
                  <% end %>

app/views/shared/_notifications.html.erb
<div class="notify-panel"
     ng-init="notifyController.unreadNotificationsCount = <%= @notifications.count %>;"
     ng-controller="NotificationsController as notifyController"
     >
  <a href="#" ng-click="notifyController.showNotificationsWindow($event)" class="notify-link">
    <div class="notify-count <%= @notifications.count == 0 ? 'notify-count_hidden' : '' %>">{{notifyController.unreadNotificationsCount}}</div>
  </a>
  <%#
    <!-- TODO: убрать img тэг, картинку навесить стилями на a -->
    <!-- <a href="#"><%= image_tag "search.png" %-></a> -->
  %>
  <div class="alarm-notifications popup-animation mobile" ng-class="$root.activePopup === 'notifications' ? 'active' : ''">
    <div class="notifications-header">
      <div class="mobile_logo"><%= link_to image_tag('logo_menu.png', alt: 'distodi.logo'), root_path %></div>
      <div class="exit_mobile" ng-click="notifyController.showNotificationsWindow($event)">
        <div class="line"></div>
        <div class="line"></div>
      </div>
      <h3 class="header-title"> <%= t(".header_title") %> </h3>
      <p>
        <span class="unread"><%= t(".unread") %></span>
        <%= link_to t(".mark_as_read"), "#" %>
      </p>
    </div>
      <ul class="notifications-list">
         <% if @notifications.count == 0 %>
           <p class="notify-description"> <%= t(".no_notifications") %> </p>
         <% else %>
           <% @notifications.each do |notification| %>
              <li class="list-item">
                <div class="status_notification"></div>
                <a href="#" ng-click='notifyController.getNotifications(<%= notification.id %>, "<%= I18n.locale %>", $event)'>
                  <%= notification.message %>
                </a>
              </li>
           <% end %>
         <% end %>
      </ul>
  </div>
</div>

app/views/shared/_passwords_edit.html.erb
              <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :put }) do |f| %>
              <%= f.hidden_field :reset_password_token %>
              <div class="mail edit_pass">
                <div class="errors_reg pass">
                  <%= resource.errors.full_messages_for(:password).join(',') %>
                </div>
                <%= f.password_field :password, autofocus: true, autocomplete: "off",placeholder: t(".new_pass") %>
                <%= inline_svg "pass_ico.svg", class: 'edit_pass_ico' %>
              </div>
              <div class="mail edit_pass second">
                <%= f.password_field :password_confirmation, autocomplete: "off",placeholder: t(".confirm") %>
                <%= inline_svg "pass_ico.svg", class: 'edit_pass_ico' %>
              </div>
              <div class="signup_but">
                <%= f.submit t(".change") %>
              </div>
              <% end %>

app/views/shared/_passwords_send.html.erb
              <%= form_for(resource, as: resource_name, url: password_path(resource_name), html: { method: :post }) do |f| %>
                <div class="mail reset_password">
                  <%= f.email_field :email, autofocus: true, placeholder: t(".email") %>
                  <%= inline_svg "mail_ico.svg" %>
                </div>
                <div class="errors_reg mail">
                  <%= resource.errors.full_messages_for(:email).join(',') %>
                </div>
                <div class="signup_but">
                  <%= f.submit t(".send") %>
                </div>
              <% end %>

app/views/shared/_registration_form.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <% if resource_name == :user %>
    <div class="name">
      <%= f.text_field :first_name, autofocus: true, placeholder: t(".name.#{resource_name}") %>
      <%= inline_svg "user_ico.svg" %>
    </div>
    <div class="errors_reg name">
      <%= resource.errors.full_messages_for(:first_name).join(',') %>
    </div>
  <% elsif resource_name == :company %>
    <div class="name">
      <%= f.text_field :name, autofocus: true, placeholder: t(".name.#{resource_name}") %>
      <%= inline_svg "user_ico.svg" %>
    </div>
    <div class="errors_reg name">
      <%= resource.errors.full_messages_for(:name).join(',') %>
    </div>
  <% end %>
  <div class="mail">
    <%= f.email_field :email, placeholder: t(".email") %>
    <%= inline_svg "mail_ico.svg" %>
  </div>
  <div class="errors_reg mail">
    <%= resource.errors.full_messages_for(:email).join(',') %>
  </div>
  <div class="password">
    <input autocomplete="off" placeholder="<%= t(".pass") %>" type="{{type}}" name="<%= resource_name %>[password]" id="<%= resource_name %>_password">
    <%= inline_svg "pass_ico.svg" %>
  </div>
  <div class="errors_reg pass">
    <%= resource.errors.full_messages_for(:password).join(',') %>
  </div>
  <div class="signup_but">
    <%= f.submit t(".create.#{resource_name}") %>
  </div>

<% end %>

app/views/shared/_registration_layout.html.erb
<div class="sign_in_content">
  <div class="left_form">
    <div class="logo_green">
      <%= link_to image_tag('logo_green.png', alt: t(".distodi")), root_path %>
      <%= link_to root_path do %>
      <div class="exit">
        <%= image_tag('cross.png', alt: t(".close")) %>
      </div>
      <% end %>
    </div>
    <div class="main_text">
      <%= t(".#{controller_name}.#{action_name}.#{resource_name}.main_text") %>
    </div>
    <div class="second_text">
      <%= t(".#{controller_name}.#{action_name}.#{resource_name}.second_text") %>
    </div>
    <div class="signup_form">
      <div class="wrapper">
        <div class="tabs">
          <div class="tab user<%= " active" if resource.is_a? User %>">
            <%= link_to(t(".client"), send(:"new_user_#{controller_name.singularize}_path")) %>
          </div>
          <div class="tab<%= " active" if resource.is_a? Company %>">
            <%= link_to(t(".company"), send(:"new_company_#{controller_name.singularize}_path")) %>
          </div>
        </div>
        <div class="tabs_content">
          <div class="tab_item">
            <div class="user_form">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
      <div class="signup_info">
        <%= (t(".#{controller_name}.#{action_name}.#{resource_name}.agreementt") % {namespace: controller.class.name.split("::").first.downcase}).html_safe %>
      </div>
      <div class="signup_info">
        <%= (t(".#{controller_name}.#{action_name}.#{resource_name}.already_have_account") % {namespace: controller.class.name.split("::").first.downcase}).html_safe %>
      </div>
    </div>
  </div>
  <div class="right_image">

  </div>
  <div class="white_box">
  </div>
</div>

app/views/shared/_registration_success.html.erb
<div class="sign_in_content">
  <div class="left_form">
    <div class="logo_green">
      <%= link_to image_tag('logo_green.png', alt: t(".distodi")), root_path %>
      <div class="exit">
        <%= link_to image_tag('cross.png', alt: t(".close")), root_path %>
      </div>
    </div>
    <div class="sent_image">
      <%= image_tag "sent.png" %>
    </div>
    <div class="main_text big">
      <%= t ".#{controller_name}.#{action_name}.#{resource_name}.success_big" %>
    </div>
    <div class="second_text">
      <%= t ".#{controller_name}.#{action_name}.#{resource_name}.success_small" %>
    </div>
    <div class="signup_form">
      <div class="done_button">
        <%= yield %>
      </div>
    </div>
  </div>
  <div class="right_image">

  </div>
  <div class="white_box">
  </div>
</div>