config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "/", to: redirect("/#{I18n.default_locale}")

  %w(facebook twitter google linkedin).each do |provider|
    devise_scope :user do
      get "/users/auth/:provider" => "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "users" }, as: :"user_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end

    devise_scope :company do
      get "/companies/auth/:provider", to: "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "companies" }, as: :"company_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    authenticate :admin_user do
      mount Sidekiq::Web => "/sidekiq"
    end
    ActiveAdmin.routes(self) rescue nil # when setting up the app routes are loaded before DB schema and ActiveAdmin can't establish connection

    devise_for :admin_users, ActiveAdmin::Devise.config
    devise_for :companies, controllers: {
      registrations: "companies/registrations",
      sessions: "companies/sessions",
      passwords: "companies/passwords",
    }
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
    }

    devise_scope :user do
      get "/users/passwords/reset_success" => "users/passwords#reset_success"
      get "/users/passwords/new_pass_success" => "users/passwords#new_pass_success"
      get "/users/registrations/success" => "users/registrations#success"
    end

    devise_scope :company do
      get "/companies/passwords/reset_success" => "companies/passwords#reset_success"
      get "/companies/passwords/new_pass_success" => "companies/passwords#new_pass_success"
      get "/companies/registrations/success" => "companies/registrations#success"
    end

    resources :leads, only: %i( new create )
    resources :attribute_kinds
    resources :service_kinds

    resources :users do
      member do
        get :services
        get :companies
      end
    end

    resources :companies do
      member do
        get :items
        get :services
        get :activate
      end
    end

    resources :items do
      collection do
        get :get_attributes
      end
      member do
        post :transfer
        post :receive
        get :show_pdf
      end
      resources :services do
        member do
          patch :approve
          patch :decline
        end
      end
      resources :charts, as: :key_performance_indicators, only: %i(index)
    end

    # TODO: remove this routes, must use that one services rousource inside the items
    resources :services do
      member do
        patch :approve
        patch :decline
      end
    end

    resources :checkouts, only: %i( show new create )

    get           "/dashboard" => "items#dashboard",          as: :dashboard
    get           "/dashboard" => "items#dashboard",          as: :home
    get         "/item/:token" => "items#show_for_company",   as: :show_for_company
    get "/item/service/:token" => "services#company_service", as: :company_service
    get           "/addresses" => "addresses#search"
    get               "/about" => "static_pages#about",       as: :static_pages_about
    get            "/security" => "static_pages#security",    as: :static_pages_security
    get         "/for_investors" => "static_pages#for_investors", as: :static_pages_for_investors
    get             "/careers" => "static_pages#careers",     as: :static_pages_careers
    get                "/lead" => "static_pages#lead",        as: :static_pages_lead
    get               "/terms" => "static_pages#terms",       as: :static_pages_terms
    get                 "/new" => "static_pages#home",        as: :static_pages_home
    get            "/donation" => "checkouts#new",            as: :donation

    post "/notifications/:id/read" => "notifications#read", constraints: ->(request) { request.xhr? }

    authenticated :user do
      root "items#dashboard", as: :authenticated_root
      get "/profile" => "users#profile"
    end

    authenticated :company do
      root "items#dashboard_company", as: :authenticated_root_company
      get "/profile" => "companies#profile"
    end
    # Temporary changed root route
    if ENV["HOME_PAGE_TRIGGER"].present?
      root "static_pages#home"
    else
      root "leads#new"
    end

    resources :blockchain_infos, path: "blockchain", param: "hash"
  end

  get "*path",
    constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" },
    to: redirect do |params, request|
      "#{request.protocol}#{request.host_with_port}/#{I18n.default_locale}/#{params[:path]}?#{request.params.to_query}"
    end
end

app/models/company.rb
class Company < ActiveRecord::Base
  # Include default devise modules. Others available are:
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include OauthableModel

  URL_REGEXP = /\A(https?:\/\/)?(www\.)?[-a-zA-Z0-9._]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.,~#?!&\/=]*)\z/

  has_many :items, as: :user
  has_many :services, through: :items
  has_many :assigned_services, foreign_key: :approver_id,
                               class_name: "Service",
                               as: :approver
  has_many :service_kinds
  has_one :profile, dependent: :nullify

  validates_presence_of :name
  validates :phone, phone: true, allow_blank: true
  validates :postal_code, presence: true, length: { is: 5 }, allow_blank: true
  validates :website, format: {with: self::URL_REGEXP}, allow_blank: true

  after_update :verification

  mount_uploader :picture, AccountUploader

  default_scope { where demo: false }
  scope :demo, -> { unscoped.where demo: true }
  scope :user_companies, lambda { |user|
    # joins(services: { item: :user }).where(users: { id: user_id })
    joins(:items).where(items: {user_id: user.id, user_type: user.class.name })
  }

  def after_sign_up_actions!
    super
    CompanyMailer.confirmation_email(self).deliver_later
  end

  def verification
    if changes["verified"] == [false, true]
      UpdateServiceStatusWorker.perform_async(id)
    end
  end

  def update_status
    assigned_services.where(status: "preapproved").each do |assigned_service|
      assigned_service.approve!
    end
  end

  def country_object
    ISO3166::Country.find_country_by_name country
  end

  def accept_invitation!
    if invited_to_sign_up?
      @accepting_invitation = true
      run_callbacks :invitation_accepted do
        accept_invitation
        confirmed_at = invitation_accepted_at if respond_to?(:confirmed_at)
        self.active = true
        save validate: false
      end.tap { @accepting_invitation = false }
    end
  end

  def map_address
    [city, address].compact.join(", ")
  end

  def to_blockchain_hash
    {
      id: id,
      verified: verified?
    }
  end
end

# == Schema Information
#
# Table name: companies
#
#  id                     :integer          not null, primary key
#  name                   :string
#  phone                  :string
#  country                :string
#  city                   :string
#  address                :string
#  postal_code            :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  website                :string
#  notice                 :string
#  first_name             :string
#  last_name              :string
#  picture                :string
#  active                 :boolean          default("true")
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  invitations_count      :integer          default("0")
#  demo                   :boolean
#  verified               :boolean          default("false")
#
# Indexes
#
#  index_companies_on_email                 (email) UNIQUE
#  index_companies_on_invitation_token      (invitation_token) UNIQUE
#  index_companies_on_invitations_count     (invitations_count)
#  index_companies_on_invited_by_id         (invited_by_id)
#  index_companies_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/companies/confirmations_controller.rb
class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/invitations_controller.rb
class Companies::InvitationsController < Devise::InvitationsController
  def accept_resource
    resource = resource_class.accept_invitation(update_resource_params)
    resource.save validate: false
    resource
  end
end

app/controllers/companies/passwords_controller.rb
class Companies::PasswordsController < Devise::PasswordsController

  layout 'new'

  prepend_before_action :require_no_authentication, except: :new_pass_success

  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(_)
    companies_passwords_new_pass_success_path
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(_)
    companies_passwords_reset_success_path
  end
end

app/controllers/companies/registrations_controller.rb
class Companies::RegistrationsController < Devise::RegistrationsController
  include Accessible

  layout 'new'

  before_action :check_user, except: :success
  before_filter :configure_sign_up_params, only: [:create]

  # before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource

  def create
    ActiveRecord::Base.transaction do
      super
      if resource.valid?
        resource.after_sign_up_actions!
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone, :website, :notice, :first_name, :last_name, :country, :city, :address, :postal_code, :picture])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  def after_sign_up_path_for(_)
    companies_registrations_success_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
class Companies::SessionsController < Devise::SessionsController
  layout 'new'
end

app/controllers/companies/unlocks_controller.rb
class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout 'item'
  before_action :set_company, only: [:show, :edit, :update, :destroy, :items, :services]
  before_action :authenticate_company!

  def show
    authorize @company
    redirect_to edit_company_path(@company)
  end

  def items
    authorize @company
    @items = @company.services.map(&:item).uniq
  end

  def services
    @pending_services = @company.assigned_services.pending
    @approved_services = @company.assigned_services.approved
    @declined_services = @company.assigned_services.declined
  end

  def edit
    authorize @company
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @company
    if @company.update(company_params)
      redirect_to root_path, notice: t(".notice")
    else
      render :edit
    end
  end

  def destroy
    authorize @company
    if @company.valid_password?(params[:company][:password])
      sign_out @company
      @company.destroy
      redirect_to root_path, notice: t(".success")
    else
      redirect_to edit_company_url, notice: t(".password_invalid")
    end
  end

  def profile
    redirect_to edit_company_path(current_company)
  end

  private

  def set_company
    @company = Company.find(params[:id])
    @company = @company.present? ? @company.decorate : @company
  end

  def company_params
    country = ISO3166::Country.find_country_by_name(params[:company][:country]) ||
              ISO3166::Country.new(params[:company][:country])
    params[:company][:country] = country.name if country.present?
    params.require(:company).permit(:name, :phone, :country, :city, :address, :website, :postal_code, :picture, :email, :notice)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<div  class="service_create_main_form"
      ng-controller="AccountEditController as accountEditController"
      ng-click="clickedBlank()"
      ng-init='accountEditController.setProfile(
         <%= @company.to_json(only: %i( country_short city address postal_code ), methods: %i( country_short profile_picture_url )).html_safe %>
       )'>

  <div class="left_form_service_create margin">
    <div class="form_service_create">
      <div class="destroy_user company">
        <h1>
          <%= t(".delete_my_account") %>
        </h1>
        <%= form_for @company, method: :delete do |f| %>
          <p>
            <%= t(".password") %>
          </p>
          <%= f.password_field :password, autocomplete: :off, placeholder: t(".password_input")  %>
          <div class="delete_button">
            <%= f.submit t(".delete_link"), data: { confirm: t(".confirm_delete") } %>
          </div>
        <% end %>
      </div>

      <%= form_for(@company) do |f| %>

        <% if @company.errors.any? %>
          <div class="error_explanation">
            <p><%= t(".errors_company") %></p>
          </div>
        <% end %>
        <div class="price">
          <p class="field_name">
            <%= t(".email_company") %>
          </p>
          <%= f.email_field :email %>
        </div>

        <div class="half_form_field half first">
          <p class="field_name">
            <%= t(".name") %>
          </p>
          <%= f.text_field :name, autofocus: true, placeholder: t(".name_placeholder")  %>
        </div>

        <div class="half_form_field half">
          <p class="field_name">
            <%= t(".website") %>
          </p>
          <%= f.text_field :website, placeholder: t(".website_placeholder")  %>
        </div>

        <div class="notification_confirmation approver">
          <div class="select">
            <label>
              <input type="checkbox" checked/>
              <i>
                <%= image_tag "select.png" %>
              </i>
              <span>
                <%= t(".approver") %>
              </span>
            </label>
          </div>
        </div>

        <div class="line"></div>

        <div class="notification_confirmation office">
          <h1><%= t(".your_office") %></h1>
          <p><%= t(".set_office") %></p>
        </div>

        <div class="half_form_field first">
          <p class="field_name">
            <%= f.label :postal_code %>
          </p>
          <%= f.text_field :postal_code, placeholder: t(".postal_example"), :"ng-model" => "postalCode", :"ng-change" => "changedPostalCode(\"#{I18n.locale}\")" %>
          <ul class="hint-list" ng-show="addresses.length > 0">
            <li ng-click="addressSelected()" ng-repeat="address in addresses">{{address.formatted_address}}</li>
          </ul>
        </div>

        <div class="half_form_field half first">
          <p class="field_name">
            <%= f.label :country %>
          </p>
          <%= f.country_select :country, {prompt: t(".select_country")}, :"ng-model" => "country", :"ng-value" => "{{country}}" %>
        </div>

        <div class="half_form_field half city">
          <p class="field_name">
            <%= f.label :city %>
          </p>
          <%= f.text_field :city, placeholder: t(".city_example"), :"ng-value" => "city" %>
        </div>

        <div class="price">
          <p class="field_name">
            <%= f.label :address %>
          </p>
          <%= f.text_field :address, placeholder: t(".address_example"), :"ng-model" => "formattedAddress"  %>
        </div>

        <div class="half_form_field margin first phone">
          <p class="field_name">
            <%= f.label :phone %>
          </p>
          <%= f.text_field :phone, placeholder: t(".phone_example")  %>
        </div>

        <p class="field_name">
          <%= t(".additional_field") %>
        </p>
        <div class="textarea">
          <%= f.text_area :notice, placeholder: t(".additional_example") %>
        </div>

        <div class="line"></div>

        <div class="change_password">
          <h1><%= t(".change_password") %></h1>
          <div class="half_form_field half first">
            <p class="field_name">
              <%= t(".original_password") %>
            </p>
            <%= f.password_field :password, autocomplete: :off,
                placeholder: t(".password_input")  %>
          </div>

          <div class="half_form_field half">
            <p class="field_name">
              <%= t(".new_password") %>
            </p>
            <%= f.password_field :password_confirmation, autocomplete: :off,
                placeholder: t(".password_confirmation_input")  %>
          </div>
        </div>
        <div class="line"></div>

        <div class="notification_confirmation">
          <h1><%= t(".notifications") %></h1>
          <div class="select">
            <label>
              <input type="checkbox" checked/>
              <i>
                <%= image_tag "select.png" %>
              </i>
              <span>
                <%= t(".receive_notifications") %>
              </span>
            </label>
          </div>
        </div>

        <div class="line"></div>
        <div class="user_destroy_place"></div>
        <div class="line"></div>
         <div class="form-actions user">
          <%= f.submit t(".confirm") %>
          <%= link_to t(".discard"), dashboard_path %>
        </div>
      </div>
    </div>

    <div class="right_form_service_create">
      <p class="field_name">
        <%= t(".picture", formats: picture_formats) %>
      </p>
      <div class="image user {{ newPhotoAttached[0] ? 'with_photo' : 'without_photo_input' }}" style="background: url({{imagePreview[0] || images[0]}}) no-repeat center center; background-size: cover;">
        <div class="blank_image">+</div>
        <%= f.file_field :picture,
                         class: 'inputfile',
                         :"data-file" => "true",
                         :"data-index" => 0,
                         :"accept" => "image/jpg, image/jpeg, image/png" %>
      </div>
    <% end %>
    <div class="service_form_info">
      <% if !current_company.verified %>
        <p class="red">
          <%= t(".unapproved_company_title") %>
        </p>
        <span class="red">
          <%= t(".unapproved_company_text").html_safe %>
        </span>
      <% end %>
      <p>
        <%= t(".title") %>
      </p>
      <span>
        <%= t(".text") %>
      </span>
    </div>
  </div>
</div>

app/views/companies/edit.html.erb
<div class="service_create_identity">
  <h1><%= t(".my_account") %></h1><div class="company_verification <%= current_company.verified %> form"></div>
  <span class="green">
    <%= current_company.items.count %>&nbsp;<%= t(".items") %>
  </span>
  <span class="grey_text">
    <%= @company.services.count %> <%= t(".services") %>
  </span>
</div>

<%= render 'form' %>

app/views/companies/items.html.erb
<div class="margin_left">

<p id="notice"><%= notice %></p>

<h1>My Items</h1>







    <% @items.each do |item| %>

        <div style="width: 300px; float: left; margin: 11px 0 0 0"><%= image_tag(item.picture_url, alt: item.title, width: 250) %>
        </div>

          <strong ><%= item.title %><br></strong>
          
      <span><%= link_to 'Add Service', company_service_path(token: item.token), class: "buttonsuser", id: "buttonsuserwidth" %></span>
      

      <br><br><br><br><br>

             <% end %>





<p><%= link_to 'Back to my panel', company_path(@company) %></p>
</div>

app/views/companies/new.html.erb
<div class="margin_left1">
  <h3>New Company</h3>
</div>
<%= render 'form' %>
<div class="margin_left">
<%= link_to 'Back', companies_path %>
</div>

app/views/companies/services.html.erb
<div class="margin_left">
<p id="notice"><%= notice %></p>

<h1>Services:</h1>

<% @all_services.each do |service| %>
      <div class="servicelist">
      <div style="width: 290px; height: 270px; float: left; margin-bottom: 20px">
      <strong><br><%= service.created_at %></strong>
    <div class="thumbnail_grid">
      <%= service_picture_show(service) %>
    </div>
    </div>

      <strong><br><% service.action_kinds.each do |action_kind| %>
          <%= "#{action_kind.title}" %>
      <% end %>
      <br></strong>
    <% service.service_fields.each do |service_field| %>
            <%= service_field.service_kind.title %><br>
         <%= service_field.text %>
    <% end %>

      
    <strong style="margin-left: 40%"><%= number_to_currency(service.price , unit: "€") %></strong>
      </div>
<% end %>

<h1>pending </h1>

<% @pending_services.each do |service| %>
      <div class="servicelist">
      <div style="width: 290px; height: 270px; float: left; margin-bottom: 20px">
      <strong><br><%= service.created_at %></strong>
    <div class="thumbnail_grid">
      <%= service_picture_show(service) %>
    </div>
    </div>

      <strong><br><% service.action_kinds.each do |action_kind| %>
          <%= "#{action_kind.title}" %>
      <% end %>
      <br></strong>
    <% service.service_fields.each do |service_field| %>
            <%= service_field.service_kind.title %><br>
         <%= service_field.text %>
    <% end %>
    <p style="color: orange;">Service is not approved</p>
      <%= link_to 'Confirm',  class: "buttonsuser" %>
      <%= link_to 'Delete',  class: "buttonsuser" %>
    <strong style="margin-left: 40%"><%= number_to_currency(service.price , unit: "€") %></strong>
      </div>
<% end %>

<h1>approved </h1>

<% @approved_services.each do |service| %>
      <div class="servicelist">
      <div style="width: 290px; height: 270px; float: left; margin-bottom: 20px">
      <strong><br><%= service.created_at %></strong>
    <div class="thumbnail_grid">
      <%= service_picture_show(service) %>
    </div>
    </div>

      <strong><br><% service.action_kinds.each do |action_kind| %>
          <%= "#{action_kind.title}" %>
      <% end %>
      <br></strong>
    <% service.service_fields.each do |service_field| %>
            <%= service_field.service_kind.title %><br>
         <%= service_field.text %>
    <% end %>
    <p style="color: green;">Service is approved</p>
      
    <strong style="margin-left: 40%"><%= number_to_currency(service.price , unit: "€") %></strong>
      </div>
<% end %>

<h1>declined </h1>

<% @declined_services.each do |service| %>
      <div class="servicelist">
      <div style="width: 290px; height: 270px; float: left; margin-bottom: 20px">
      <strong><br><%= service.created_at %></strong>
    <div class="thumbnail_grid">
      <%= service_picture_show(service) %>
    </div>
    </div>

      <strong><br><% service.action_kinds.each do |action_kind| %>
          <%= "#{action_kind.title}" %>
      <% end %>
      <br></strong>
    <% service.service_fields.each do |service_field| %>
            <%= service_field.service_kind.title %><br>
         <%= service_field.text %>
    <% end %>
    <p style="color: red;">Service is declined</p>
      
    <strong style="margin-left: 40%"><%= number_to_currency(service.price , unit: "€") %></strong>
      </div>
<% end %>

  <div style="width: 100%">
  <%= link_to 'Back', @company,  class: "buttonsuser" %></div>
</div>

app/views/companies/show.html.erb
<div class="margin_left">

<p id="notice"><%= notice %></p>
<div class="thumbnail">
  <%= picture_show(@company) %>
</div>
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @company.phone %>
</p>

<p>
  <strong>Country:</strong>
  <%= @company.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @company.postal_code %>
</p>

<%= link_to t(".edit_link"), edit_company_path(@company) %>

<span><%= link_to t(".delete_link"), company_path(@company), method: :delete,:data => {:confirm => t(".confirm_delete")}, class: "buttonsuser" %></span>

<h2>Assigned Services:</h2>
<%= render "services/list", list: @company.assigned_services, current_user: current_company %>

<h2>Performed Services:</h2>
<%= render "services/list", list: @company.services, current_user: current_company %>