config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "/", to: redirect("/#{I18n.default_locale}")

  %w(facebook twitter google linkedin).each do |provider|
    devise_scope :user do
      get "/users/auth/:provider" => "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "users" }, as: :"user_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end

    devise_scope :company do
      get "/companies/auth/:provider", to: "omniauth_callbacks#passthru", defaults: { provider: provider, resource: "companies" }, as: :"company_#{provider}_omniauth_authorize"
      get "/auth/#{provider}/callback" => "omniauth_callbacks#default_callback", defaults: { provider: provider }
    end
  end

  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    authenticate :admin_user do
      mount Sidekiq::Web => "/sidekiq"
    end
    ActiveAdmin.routes(self) rescue nil # when setting up the app routes are loaded before DB schema and ActiveAdmin can't establish connection

    devise_for :admin_users, ActiveAdmin::Devise.config
    devise_for :companies, controllers: {
      registrations: "companies/registrations",
      sessions: "companies/sessions",
      passwords: "companies/passwords",
    }
    devise_for :users, controllers: {
      registrations: "users/registrations",
      sessions: "users/sessions",
      passwords: "users/passwords",
    }

    devise_scope :user do
      get "/users/passwords/reset_success" => "users/passwords#reset_success"
      get "/users/passwords/new_pass_success" => "users/passwords#new_pass_success"
      get "/users/registrations/success" => "users/registrations#success"
    end

    devise_scope :company do
      get "/companies/passwords/reset_success" => "companies/passwords#reset_success"
      get "/companies/passwords/new_pass_success" => "companies/passwords#new_pass_success"
      get "/companies/registrations/success" => "companies/registrations#success"
    end

    resources :leads, only: %i( new create )
    resources :attribute_kinds
    resources :service_kinds

    resources :users do
      member do
        get :services
        get :companies
      end
    end

    resources :companies do
      member do
        get :items
        get :services
        get :activate
      end
    end

    resources :items do
      collection do
        get :get_attributes
      end
      member do
        post :transfer
        post :receive
        get :show_pdf
      end
      resources :services do
        member do
          patch :approve
          patch :decline
        end
      end
      resources :charts, as: :key_performance_indicators, only: %i(index)
    end

    # TODO: remove this routes, must use that one services rousource inside the items
    resources :services do
      member do
        patch :approve
        patch :decline
      end
    end

    resources :checkouts, only: %i( show new create )

    get           "/dashboard" => "items#dashboard",          as: :dashboard
    get           "/dashboard" => "items#dashboard",          as: :home
    get         "/item/:token" => "items#show_for_company",   as: :show_for_company
    get "/item/service/:token" => "services#company_service", as: :company_service
    get           "/addresses" => "addresses#search"
    get               "/about" => "static_pages#about",       as: :static_pages_about
    get            "/security" => "static_pages#security",    as: :static_pages_security
    get         "/for_investors" => "static_pages#for_investors", as: :static_pages_for_investors
    get             "/careers" => "static_pages#careers",     as: :static_pages_careers
    get                "/lead" => "static_pages#lead",        as: :static_pages_lead
    get               "/terms" => "static_pages#terms",       as: :static_pages_terms
    get                 "/new" => "static_pages#home",        as: :static_pages_home
    get            "/donation" => "checkouts#new",            as: :donation

    post "/notifications/:id/read" => "notifications#read", constraints: ->(request) { request.xhr? }

    authenticated :user do
      root "items#dashboard", as: :authenticated_root
      get "/profile" => "users#profile"
    end

    authenticated :company do
      root "items#dashboard_company", as: :authenticated_root_company
      get "/profile" => "companies#profile"
    end
    # Temporary changed root route
    if ENV["HOME_PAGE_TRIGGER"].present?
      root "static_pages#home"
    else
      root "leads#new"
    end

    resources :blockchain_infos, path: "blockchain", param: "hash"
  end

  get "*path",
    constraints: lambda { |req| !req.path.starts_with? "/#{I18n.default_locale}/" },
    to: redirect do |params, request|
      "#{request.protocol}#{request.host_with_port}/#{I18n.default_locale}/#{params[:path]}?#{request.params.to_query}"
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :characteristics
  has_many :attribute_kinds, through: :characteristics
  has_many :action_kinds, through: :category
  has_many :services, dependent: :destroy
  belongs_to :category
  belongs_to :user, polymorphic: true
  belongs_to :transferring_to, class_name: "User",
                               foreign_key: :transferring_to_id
  has_one :blockchain_transaction_datum, inverse_of: :service, dependent: :destroy

  validates :title, uniqueness: { scope: [:user_id] }, presence: true
  validates :picture, presence: true
  validates :comment, length: { maximum: 2000 }

  accepts_nested_attributes_for :characteristics

  include IdCodeable

  mount_uploader :picture, ItemUploader
  mount_uploader :picture2, ItemUploader
  mount_uploader :picture3, ItemUploader
  mount_uploader :picture4, ItemUploader
  mount_uploader :picture5, ItemUploader

  scope :without_demo, -> { where demo: false }
  scope :with_demo, -> { unscope(where: :demo) }
  scope :unconfirmed_services, -> { joins(:services).where("services.company_id IS NOT NULL AND services.confirmed IS NULL") }

  default_scope { without_demo }

  after_create :ensure_token

  def self.to_csv(item)
    data = item.characteristics.includes(:attribute_kind).map do |c|
      [c.attribute_kind.title, c.value]
    end
    data << [""]

    CSV.generate { |csv| data.each { |line| csv << line } } +
    Service.to_csv(item.services)
  end

  def characteristics_ordered
    characteristics.joins(:attribute_kind).order("attribute_kinds.position")
  end

  def to_blockchain_hash
    {
      id: id,
      user_id: user_id,
      user_type: user_type,
      transferring_to_id: transferring_to_id,
      category:   {
        id: category.id,
      }
    }
  end

  private

  def generate_token
    loop do
      token = Devise.friendly_token.downcase
      break token unless self.class.exists?(token: token)
    end
  end

  def ensure_token
    self.update_attribute(:token, generate_token) if self.token.blank?
  end
end

# == Schema Information
#
# Table name: items
#
#  id                 :integer          not null, primary key
#  title              :string
#  category_id        :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :integer
#  picture            :string
#  token              :string
#  id_code            :string
#  transferring_to_id :integer
#  demo               :boolean
#  picture2           :string
#  picture3           :string
#  picture4           :string
#  picture5           :string
#  comment            :string(2000)
#  user_type          :string
#  archivation        :boolean          default("false")
#  archived           :boolean          default("false")
#  deleted_at         :datetime
#
# Indexes
#
#  index_items_on_category_id  (category_id)
#  index_items_on_deleted_at   (deleted_at)
#

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  layout 'item', except: [:show_for_company]

  before_action :set_item, only: [:show, :edit, :update, :destroy, :transfer,
                                  :receive, :show_pdf]
  before_action :authenticate_user_or_company!
  before_action :set_order, only: %i( show dashboard )

  def index
    @items = Item.unscoped.where(user: current_user_or_company)
  end

  def dashboard
    @items = Item.unscoped.where(user: current_user_or_company)
    @services = Service.unscoped
      .includes(:item, :company, :approver, :action_kinds, :service_fields => :service_kind)
      .where(item: @items)
      .joins("LEFT JOIN service_fields ON services.id = service_fields.service_id")
      .joins("LEFT JOIN service_kinds ON service_fields.service_kind_id = service_kinds.id")
      .joins("LEFT JOIN service_action_kinds ON services.id = service_action_kinds.service_id")
      .joins("LEFT JOIN action_kinds ON service_action_kinds.action_kind_id = action_kinds.id")
      .order(dashboard_order_params)
      .decorate
  end

  def show
    @items = Item.unscoped.where(user: current_user_or_company)
    @services = @item.services.includes(:service_fields, :action_kinds)
      .joins("LEFT JOIN service_fields ON services.id = service_fields.service_id")
      .joins("LEFT JOIN service_kinds ON service_fields.service_kind_id = service_kinds.id")
      .joins("LEFT JOIN service_action_kinds ON services.id = service_action_kinds.service_id")
      .joins("LEFT JOIN action_kinds ON service_action_kinds.action_kind_id = action_kinds.id")
      .order(dashboard_order_params)
      .decorate
    respond_to do |format|
      format.html { render "dashboard" }
      format.csv { send_data Item.to_csv(@item) }
    end
  end

  def new
    @item = current_user_or_company.items.build
    @item.check_user_attributes
    @items = [@item]
    @attributes = AttributeKind.all
  end

  def create
    @items = current_user_or_company.items
    @item = Item.new(item_params)
    @item.user = current_user_or_company

    @item.characteristics = characteristics_params.map do |key, value|
      attribute_kind = @item.category.attribute_kinds.find(key)
      Characteristic.new(attribute_kind: attribute_kind, value: value)
    end if characteristics_params.any?

    if @item.save
      blockchain_transaction!
      redirect_to @item, notice: t(".notice")
    else
      render :new
    end
  end

  def edit
    @items = [@item]
    authorize @item
    @services = current_user_or_company.services.includes(:service_fields, :action_kinds).decorate
  end

  def update
    authorize @item

    if characteristics_params.any?
      characteristics_params.select { |_, v| v.present? }.map do |key, value|
        characteristic = @item.characteristics.find { |c| c.attribute_kind_id == key.to_i }
        if characteristic.present?
          if characteristic.value.blank?
            characteristic.update(value: value)
          end
        else
          attribute_kind = @item.category.attribute_kinds.find(key)
          @item.characteristics << Characteristic.new(attribute_kind: attribute_kind, value: value)
        end
      end
    end

    if @item.update(update_item_params)
      redirect_to @item
    else
      render :edit
    end
  end

  def destroy
    authorize @item
    if current_user_or_company.valid_password?(params[:item][:password])
      @item.destroy
      redirect_to dashboard_path, notice: t(".success")
    else
      redirect_to :back, notice: t(".password_invalid")
    end
  end

  def dashboard_company
    @services = current_company.assigned_services.includes(:item)
    @items = @services.map(&:item).uniq
    render "empty_items_services" if @items.blank?
  end

  def show_for_company
    @item = Item.find_by(token: params[:token]) || Item.new
    authorize @item
  end

  def get_attributes
    @item = if params[:item_id].present?
      Item.unscoped.where(id: params[:item_id]).first.tap { |item| authorize item }
    else
      current_user_or_company.items.build
    end
    @item = @item.decorate context: { category_id: params[:category_id],
                                      brand_option_id: params[:brand_option_id] }
  end

  def transfer
    authorize @item
    validator = ItemTransferValidator.new(params)
    if validator.valid?
      TransferService.new(@item, params[:user_identifier], current_user_or_company).perform
      flash[:notice] = t(".success")
    else
      flash[:error] = validator.errors.join(". ")
    end
    redirect_to edit_item_path(@item)
  end

  def receive
    authorize @item
    @item.update user: current_user_or_company, transferring_to: nil
    redirect_to action: :index
  end

  def show_pdf
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Distodi_report",
        header: { html: { template: "items/pdf_header.html.erb" } },
        template: "items/show_pdf.html.erb",
        layout: 'pdf.html',
        footer: { html: { template: "items/pdf_footer.html.erb" } }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.unscoped.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:title, :picture, :picture2, :picture3, :picture4, :picture5, :category_id, :token, :comment)
  end

  def update_item_params
    params.require(:item).permit(:title, :picture, :picture2, :picture3, :picture4, :picture5, :comment)
  end

  def characteristics_params
    category = if @item.present?
      @item.category
    elsif item_params[:category_id].present?
      Category.find(item_params[:category_id])
    end
    attribute_kind_ids = if category.present?
      category.attribute_kinds.pluck(:id).map(&:to_s)
    else
      []
    end
    params.require(:item).require(:characteristics).permit(attribute_kind_ids)
  end

  def set_order
    @order = Struct.new(:service_kind, :service_kind?, :service_type, :service_type?)

    service_kind_directions = Struct.new(:direction, :opposite_direction).new(
      *(order_params.column != "service_kind" || order_params.direction == "desc" ? ["desc", "asc"] : ["asc", "desc"])
    )
    service_type_directions = Struct.new(:direction, :opposite_direction).new(
      *(order_params.column != "service_type" || order_params.direction == "desc" ? ["desc", "asc"] : ["asc", "desc"])
    )

    @order = case order_params.column
    when "service_kind"
      @order.new(service_kind_directions, true, service_type_directions, false)
    when "service_type"
      @order.new(service_kind_directions, false, service_type_directions, true)
    else
      @order.new(service_kind_directions, false, service_type_directions, false)
    end
  end

  def dashboard_order_params
    case order_params.column
    when "service_kind"
      "service_kinds.title #{order_params.direction}"
    when "service_type"
      "action_kinds.title #{order_params.direction}"
    else
      "service_kinds.title ASC"
    end
  end

  def order_params
    sort_attributes = (params[:order] || "").split(" ").presence || ["service_kind", "asc"]
    Struct.new(:column, :direction).new(*sort_attributes)
  end
end

app/views/items/_items.html.erb
        <div class="slider_mobile_items">
          <div class="large-12 columns">
            <div id="owl-example_mobile_items" class="owl-carousel"
                 ng-show="controller.showDetails === undefined">
              <% if @items.count != 1 %>
                <div class="items">
                  <%= link_to root_path, class: (@item.blank? ? "active" : "") do %>
                  <div class="all_items">
                    <span><%= t(".all") %></span>
                  </div>
                  <% end %>
                </div>
              <% end %>

              <% @items.each do |item| %>
                <div class="items">
                  <%= link_to item, class: (@item.present? && item == @item ? "active" : "") do %>
                    <%= image_tag(item.picture.mini.url, alt: item.title) %>
                  <% end %>
                </div>
              <% end %>
              <% if current_user %>
                <% if current_user.transferring_items.any? %>
                  <% current_user.transferring_items.each do |item| %>
                    <div class="transfer_panel">
                      <%= image_tag(item.picture_url, alt: item.title) %>
                      <div class="red_col">
                        <div class="view">
                          <%= t ".transferred_items" %>
                        </div>
                        <div class="receive">
                          <strong><%= item.title %></strong>
                          <p><%= link_to t(".receive_item"), receive_item_path(item), method: "POST" %></p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              <% end %>
              <div class="items">
                <%= link_to new_item_path do %>
                  <div class="all_items add">
                    <p>+</p>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

app/views/items/dashboard.html.erb
<div ng-controller="ItemsController as controller"
     ng-init='controller.checkboxes.length = <%= @services.size %>;
              controller.permissions = <%= @services.map { |s| s.permissions(current_user) }.to_json.html_safe %>;
              controller.ids = <%= @services.map(&:id) %>;
              '>
  <%= render @items.present? ? "items" : "empty_items" %>

  <div>
    <% if @item.present? %>
      <div class="item_info">
        <span><%= @item.title %>, </span>
         <% @item.characteristics_ordered.each do |characteristic| %>
          <span> <%= characteristic.value %></span>
        <% end %>
      </div>
    <% elsif @items.blank? %>
      <div class="item_info">
        <span><%= link_to t(".add_your_first_item"), new_item_path %></span>
      </div>
    <% else %>
      <div class="item_info">
        <span><%= t(".all_services") %></span>
      </div>
    <% end %>
    <% if @services.any? %>
      <div class="service_count">
        <%= @services.count %> <span><%= t(".services") %></span>
      </div>
      <% if @item.present? %>
        <div class="kpi_icon">
          <%= link_to t(".kpi"), item_key_performance_indicators_path(@item) %>
        </div>
      <% end %>
    <% end %>
    <%= link_to new_item_service_path(item_id: @item), "ng-show" => "!controller.serviceActions.show" do %>
      <div class="add_service">
        <%= t(".add_new_service") %>
      </div>
    <% end if @item.present? %>
    <div class="service_panel" ng-show="controller.serviceActions.show">
      <% if @item.present? %>
        <%= link_to image_tag('pdf-icon.png'), show_pdf_item_path(@item, format: :pdf), class: "bar" %>
        <%= link_to image_tag('csv-icon.png'), item_path(@item, format: :csv) %>
      <% end %>
      <a href="" class="view"
         ng-class="controller.serviceActions.view ? '' : 'disabled'"
         ng-click="controller.clickedView('<%= I18n.locale %>')">
        <%= t(".view") %>
      </a>
      <a href="" class="delete"
         ng-class="controller.serviceActions.delete ? '' : 'disabled'"
         ng-click="controller.clickedDelete('<%= I18n.locale %>')">
        <%= t(".del") %>
      </a>
      <!-- <a href="#"><%= image_tag "send.png" %> Send</a> -->
    </div>
    <table class="list_items">
      <thead>
        <th>
          <div class="select">
            <label>
              <input type="checkbox" ng-change="controller.clickedAllCheckbox()"
                                     ng-model="controller.checkboxes.all" />
              <i ng-class="!controller.checkboxes.areAllChecked() && controller.checkboxes.isAnyChecked() ? 'partial' : ''">
                <%= image_tag "select.png" %>
              </i>
            </label>
          </div>
        </th>
        <th>
          <%= link_to t(".service"), "?order=service_kind+#{@order.service_kind.opposite_direction}",
            type: "button",
            name: "button",
            class: "sort-by#{ @order.service_kind? ? " active-sort-#{@order.service_kind.direction}" : "" }" %>
        </th>
        <th>
          <%= link_to t(".type"), "?order=service_type+#{@order.service_type.opposite_direction}",
          type: "button",
          name: "button",
          class: "sort-by#{ @order.service_type? ? " active-sort-#{@order.service_type.direction}" : "" }" %>
        </th>
        <th class="status"><%= t(".status") %></th>
        <th><%= t(".blockchain") %></th>
        <th><%= t(".item") %></th>
        <th><%= t(".company") %></th>
        <th class="date"><%= t(".date") %></th>
        <th class="cost"><%= t(".cost") %></th>
        <th></th>
      </thead>
      <tbody>
        <% @services.each.with_index do |service, i| %>
          <tr ng-class="[
                          (controller.showDetails === <%= i %> ? 'viewing' : ''),
                          (controller.checkboxes[<%= i %>] ? 'selected' : '')
                        ].join(' ')">
            <td>
              <div class="select">
                <label>
                  <input type="checkbox" ng-model="controller.checkboxes[<%= i %>]"
                                         ng-change="controller.changedCheckbox(<%= i %>)" />
                  <i>
                    <%= image_tag "select.png" %>
                  </i>
                </label>
              </div>
            </td>
            <td>
              <%= link_to service_path(service) do %>
                <% service.service_fields.each do |service_field| %>
                  <%= service_field.service_kind.title %>
                  <%= service_field.text %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to service_path(service) do %>
                <% service.action_kinds.decorate.each do |action_kind| %>
                  <div class="icon_service <%= action_kind.icon_class %>">
                    <%= "#{action_kind.title}" %>
                  </div>
                <% end %>
              <% end %>
            </td>
            <td>
              <%= link_to service_path(service) do %>
                <div class="<%= service.status %>">&nbsp;</div>
              <% end %>
            </td>
            <td class="blockchain_link">
              <%= if service.blockchain_transaction_datum.present? && service.blockchain_transaction_datum.in_blockchain?
                link_to(
                  service.short_blockchain_hash,
                  blockchain_info_path(service.blockchain_transaction_datum.blockchain_hash)
                )
              end %>
            </td>
            <td>
              <%= link_to edit_item_path(service.item) do %>
                <span><%= service.item.title %></span>
                <% service.item.characteristics_ordered.each do |characteristic| %>
                  <span> <%= characteristic.value %></span>
                <% end %>
              <% end %>
            </td>
            <td class="company">
              <% if service.approver.present? %>
                <%= service.approver.name %>
                <div class="company_verification <%= service.approver.verified %>"></div>
              <% end %>
            </td>
            <td class="date">
              <%= link_to service_path(service) do %>
                <%= service.created_at.strftime("%d %b %Y")%></td>
              <% end %>
            <td class="cost">
              <%= link_to service_path(service) do %>
                <%= number_to_currency(service.price , unit: "EUR ") %>
              <% end %>
            </td>
            <td class="actions">
              <%= link_to "&nbsp;".html_safe, service_path(service) %>
            </td>
          </tr>
        <% end %>
        <% if @services.blank? %>
          <% 10.times do %>
            <tr>
              <td>
                <div class="square"></div>
              </td>
              <td>
                <div class="line"></div>
              </td>
              <td>
                <div class="line"></div>
              </td>
              <td></td>
              <td>
                <div class="line"></div>
              </td>
              <td>
                <div class="line"></div>
              </td>
              <td>
                <div class="line"></div>
              </td>
              <td></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <div class="list_items_mobile">
      <% @services.each_with_index do |service, i| %>
      <div class="service_mobile">
        <div class="select">
          <label>
            <input type="checkbox" ng-model="controller.checkboxes[<%= i %>]"
                                   ng-change="controller.changedCheckbox(<%= i %>)" />
            <i>
              <%= image_tag "select.png" %>
            </i>
          </label>
        </div>
        <p class="type"><% service.service_fields.each do |service_field| %>
          <%= service_field.service_kind.title %>
          <%= service_field.text %>
          <% end %>
        </p>
        <% service.action_kinds.decorate.each do |action_kind| %>
              <div class="icon_service <%= action_kind.icon_class %>">
                <%= "#{action_kind.title}" %>
              </div>
        <% end %>
        <p><%= service.item.try :title %></p>
        <p><span><%= service.created_at.strftime("%d %b %Y")%></span>
        <span> <%= number_to_currency(service.price , unit: "EUR ") %></span></p>
      </div>
      <% end %>
    </div>
    <% if @items.present? && @services.blank? %>
      <div class="first_service">
        <p>
          <%= t(".service_log") %>
          <% if @item.present? %>
            <%= link_to t(".add_first_service"), new_item_service_path(item_id: @item), "ng-show" => "!controller.serviceActions.show" %>
          <% else %>
            <%= t(".add_first_service") %>
          <% end %>
        </p>
      </div>
    <% end %>
    <% if @items.blank? && @services.blank? %>
      <div class="first_service">
        <p>
          <%= t(".service_log") %>
          <%= link_to t(".add_first_item"),new_item_path, "ng-show" => "!controller.serviceActions.show" %>
        </p>
      </div>
    <% end %>
    <% if @items.present? && @services.blank? %>
      <div class="first_service_mobile">
        <p>
          <%= t(".service_log") %>
        </p>
        <% if @item.present? %>
          <%= link_to t(".add_first_service"),new_service_path(item_id: @item) %>
        <% else %>
          <p><%= t(".add_first_service") %></p>
        <% end %>
      </div>
      <div class="service_maket_mobile">
        <div class="square"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
      <div class="service_maket_mobile">
        <div class="square"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
      <div class="service_maket_mobile">
        <div class="square"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
    <% elsif @items.blank? && @services.blank? %>
      <div class="first_service_mobile">
        <p><%= t(".service_log") %></p>
        <%= link_to t(".add_first_item"), new_item_path %>
      </div>
      <div class="service_maket_mobile">
        <div class="square"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
      <div class="service_maket_mobile">
        <div class="square"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
      <div class="service_maket_mobile">
        <div class="square"></div>
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
      </div>
    <% end %>
  </div>

  <!-- Angular-tour -->
  <tour step="currentStep" post-step="postStepCallback()">
    <virtual-step
      tourtip="<%= t(".tour.welcome") %>"
      tourtip-next-label="<%= t(".tour.control.next") %>"
      tourtip-placement="bottom"
      tourtip-container-element="body"
      use-source-scope="false"
      tourtip-element=".item_logo img">
    </virtual-step>
    <%- if controller.action_name == "show" -%>
      <virtual-step
        tourtip="<%= t(".tour.start_here") %>"
        tourtip-next-label="<%= t(".tour.control.next") %>"
        tourtip-placement="bottom"
        tourtip-container-element="body"
        use-source-scope="false"
        tourtip-element=".add_service">
      </virtual-step>
    <%- end -%>
    <virtual-step
      tourtip="<%= t(".tour.add_item") %>"
      tourtip-next-label="<%= t(".tour.control.next") %>"
      tourtip-placement="bottom"
      tourtip-container-element="body"
      use-source-scope="false"
      tourtip-element=".owl-item:last-child">
    </virtual-step>
    <virtual-step
      tourtip="<%= t(".tour.find_item") %>"
      tourtip-next-label="<%= t(".tour.control.next") %>"
      tourtip-placement="bottom"
      tourtip-container-element="body"
      use-source-scope="false"
      tourtip-element=".all_items">
    </virtual-step>
    <%- if @items.present? && @services.blank? -%>
      <virtual-step
        tourtip="<%= t(".tour.services") %>"
        tourtip-next-label="<%= t(".tour.control.next") %>"
        tourtip-placement="bottom"
        tourtip-container-element="body"
        use-source-scope="false"
        tourtip-element=".first_service">
      </virtual-step>
    <%- end -%>
    <virtual-step
      tourtip="<%= t(".tour.unique_id") %>"
      tourtip-next-label="<%= t(".tour.control.next") %>"
      tourtip-placement="top"
      tourtip-container-element="body"
      use-source-scope="false"
      tourtip-element=".list_items th:nth-child(6)">
    </virtual-step>
    <virtual-step
      tourtip="<%= t(".tour.money_total") %>"
      tourtip-next-label="<%= t(".tour.control.next") %>"
      tourtip-placement="top"
      tourtip-container-element="body"
      use-source-scope="false"
      tourtip-element=".list_items th:nth-child(8)">
    </virtual-step>
    <virtual-step
      tourtip="<%= t(".tour.reporting_save") %>"
      tourtip-next-label="<%= t(".tour.control.close") %>"
      tourtip-placement="top"
      tourtip-container-element="body"
      use-source-scope="false"
      tourtip-element=".xls_button a">
    </virtual-step>
  </tour>
</div>